# Generated by Django 2.0.5 on 2018-05-30 01:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user', models.TextField()),
                ('model', models.TextField(blank=True, null=True)),
                ('model_type', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_status', models.TextField()),
                ('backup_time', models.TextField()),
                ('input_name', models.TextField(default='none')),
                ('computer_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='computermonitor.Computer')),
            ],
        ),
    ]
