# Generated by Django 2.0.5 on 2018-06-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='manufacturer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='manufacturer_site',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='serial_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
