# Generated by Django 2.0.5 on 2018-06-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermonitor', '0002_auto_20180602_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='platform',
            field=models.IntegerField(choices=[(1, 'Windows'), (2, 'Macintosh'), (3, 'Linux')], default=1),
        ),
    ]
