# Generated by Django 2.0.5 on 2018-06-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermonitor', '0003_computer_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerbackup',
            name='backup_time',
            field=models.DateTimeField(),
        ),
    ]
