# Generated by Django 2.0.5 on 2018-06-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermonitor', '0004_auto_20180608_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerbackup',
            name='backup_time',
            field=models.TextField(),
        ),
    ]
