# Generated by Django 2.0.5 on 2018-06-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermonitor', '0006_auto_20180609_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='schedule_backup_day',
            field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], default=1),
        ),
    ]
