# Generated by Django 2.0.5 on 2018-06-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermonitor', '0007_computer_schedule_backup_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='schedule_backup_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
