# Generated by Django 2.0.5 on 2018-06-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computermonitor', '0008_computer_schedule_backup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='schedule_backuptimes',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Manual')], default=2),
        ),
    ]
